# Generated by Django 5.1.6 on 2025-11-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='student_id',
            field=models.BigIntegerField(),
        ),
    ]
